### PR TITLE
close active nav on site title click, close #26

### LINKED ISSUE #26: Site title click doesn't close active nav
💃

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by mixcas** [comment]
Code is fine but those it even matter? Clicking the logo refreshes the whole site, should this be a different issue?

**Comment by mikeyrayvon** [comment]
it doesnt refresh the whole site

**Comment by mixcas** [comment]
It does. If you don't move the map to test it look like it doesn't but move the map before clicking it and you will notice the fast refresh.

**Comment by mikeyrayvon** [comment]
it doesn't. go onto the production site and test there. and if you dont believe that, where in this line is there a link to refresh the page: `<h1 id="header-name" class="u-pointer"><?php bloginfo('name'); ?></h1>`

**Comment by varffs** [comment]
It def does not refresh the page. I see inconsistent flash when clicking that link which I think is an issue with animation/moveMap()

**Pull request merged**
